version: "3"

services:
  web:
    image: ruby:2.0.0-slim
    container_name: ruby2
    tty: true
    volumes:
      - ./cp345:/cp345
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dennisoliveira/rails4
    container_name: ruby2rails4-app
    tty: true
    volumes:
      - ./app:/app
    networks:
      default:
        ipv4_address: 172.31.0.2

networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: 172.31.0.0/24